upstream weather_backend {
    server web:8000;
}

server {
    listen 80;
    server_name weatherforcast.click;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name weatherforcast.click;

    ssl_certificate     /etc/letsencrypt/live/weatherforcast.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/weatherforcast.click/privkey.pem;

    location / {
        limit_req zone=req_limit;
        limit_conn conn_limit 5;

        proxy_pass http://weather_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
